#!/usr/bin/env python3
"""Print a derived snapshot of project status — packages, Protocols, ADRs.

Onboarding to "what exists" otherwise means stitching together the source tree,
``core/protocols.py``, and every ADR header (TODO #4). This derives that view
fresh from the repository on each run, so it cannot go stale. The *human*-declared
state — who owns which lane and which ADR numbers are in flight — deliberately
stays in ``WORKING.md`` (its rightful home); this points there rather than
duplicating it.

Run via ``just status`` (or ``python3 scripts/project_status.py``). Pass
``--root`` to point at a different checkout (used by the tests).
"""

from __future__ import annotations

import argparse
import ast
import re
from dataclasses import dataclass
from pathlib import Path

_STATUS_RE = re.compile(r"^\s*-\s*Status:\s*(.+?)\s*$", re.IGNORECASE | re.MULTILINE)
_HEADING_RE = re.compile(r"^#\s*\d+\.\s*(.+?)\s*$", re.MULTILINE)
_ADR_FILE_RE = re.compile(r"^(\d+)-.*\.md$")


@dataclass(frozen=True)
class Package:
    """A package under ``src/ai_assistant`` and how much of it is built."""

    name: str
    modules: int  # .py files other than __init__.py

    @property
    def built(self) -> bool:
        """Whether the package has implementation beyond its contract docstring."""
        return self.modules > 0


@dataclass(frozen=True)
class Adr:
    """A decision record: its number, status, and title."""

    number: int
    status: str
    title: str


def discover_packages(pkg_root: Path) -> list[Package]:
    """Return the packages under ``pkg_root``, each with its module count.

    Args:
        pkg_root: The ``ai_assistant`` package directory.

    Returns:
        One :class:`Package` per child directory that has an ``__init__.py``,
        sorted by name.
    """
    packages: list[Package] = []
    for child in sorted(pkg_root.iterdir()):
        if not child.is_dir() or not (child / "__init__.py").exists():
            continue
        modules = sum(1 for p in child.glob("*.py") if p.name != "__init__.py")
        packages.append(Package(name=child.name, modules=modules))
    return packages


def protocol_names(protocols_path: Path) -> list[str]:
    """Return the names of the ``Protocol`` classes defined in ``protocols_path``.

    Args:
        protocols_path: Path to ``core/protocols.py``.

    Returns:
        Protocol class names, in source order.
    """
    tree = ast.parse(protocols_path.read_text(encoding="utf-8"))
    names: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and any(_is_protocol_base(b) for b in node.bases):
            names.append(node.name)
    return names


def _is_protocol_base(base: ast.expr) -> bool:
    """Whether a class base refers to ``Protocol`` (bare or ``typing.Protocol``)."""
    if isinstance(base, ast.Name):
        return base.id == "Protocol"
    return isinstance(base, ast.Attribute) and base.attr == "Protocol"


def adr_entries(adr_dir: Path) -> list[Adr]:
    """Return the ADRs in ``adr_dir`` (excluding the template), sorted by number.

    Args:
        adr_dir: The ``docs/adr`` directory.

    Returns:
        One :class:`Adr` per numbered record.
    """
    entries: list[Adr] = []
    for path in adr_dir.glob("*.md"):
        match = _ADR_FILE_RE.match(path.name)
        if match is None:
            continue  # template.md and other non-numbered files
        text = path.read_text(encoding="utf-8")
        status = _STATUS_RE.search(text)
        title = _HEADING_RE.search(text)
        entries.append(
            Adr(
                number=int(match.group(1)),
                status=status.group(1) if status else "?",
                title=title.group(1) if title else path.stem,
            )
        )
    return sorted(entries, key=lambda a: a.number)


def missing_numbers(numbers: list[int]) -> list[int]:
    """Return the gaps in a numbering — values absent between its min and max."""
    if not numbers:
        return []
    present = set(numbers)
    return [n for n in range(min(numbers), max(numbers) + 1) if n not in present]


def render(root: Path) -> str:
    """Build the full status report for the checkout at ``root``."""
    packages = discover_packages(root / "src" / "ai_assistant")
    protocols = protocol_names(root / "src" / "ai_assistant" / "core" / "protocols.py")
    adrs = adr_entries(root / "docs" / "adr")
    gaps = missing_numbers([a.number for a in adrs])

    lines = [
        "ai-assistant — project status",
        "(generated by `just status`; derived from the repo, never hand-edited)",
        "",
        "Packages (src/ai_assistant/)",
    ]
    width = max((len(p.name) for p in packages), default=0)
    for pkg in packages:
        state = "built" if pkg.built else "stub "
        detail = f"{pkg.modules} module(s)" if pkg.built else "contract only"
        lines.append(f"  {state}  {pkg.name.ljust(width)}  {detail}")

    lines += ["", "Protocols (core/protocols.py)"]
    lines += [f"  {name}" for name in protocols] or ["  (none)"]

    lines += ["", "ADRs (docs/adr/)"]
    for adr in adrs:
        lines.append(f"  {adr.number:04d}  {adr.status.ljust(8)}  {adr.title}")
    if gaps:
        pretty = ", ".join(f"{n:04d}" for n in gaps)
        lines.append(f"  ! gap(s): {pretty} — claimed but not on this branch (see WORKING.md)")

    lines += [
        "",
        "Ownership & work in flight",
        "  Lane owners and in-flight ADR numbers are human-maintained in WORKING.md.",
    ]
    return "\n".join(lines)


def main() -> None:
    """Parse ``--root`` and print the status report."""
    parser = argparse.ArgumentParser(description="Print a derived project-status snapshot.")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root to inspect (defaults to this checkout).",
    )
    args = parser.parse_args()
    print(render(args.root))


if __name__ == "__main__":
    main()
